# Generated by Django 3.2.18 on 2023-03-27 16:45

import datetime
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, max_length=10)),
                ('time', models.TimeField(blank=True, choices=[(datetime.time(5, 0), '5 PM'), (datetime.time(5, 30), '5:30 PM'), (datetime.time(6, 0), '6 PM'), (datetime.time(6, 30), '6:30 PM'), (datetime.time(7, 0), '7 PM'), (datetime.time(7, 30), '7:30 PM'), (datetime.time(8, 0), '8 PM'), (datetime.time(8, 30), '8:30 PM'), (datetime.time(9, 0), '9 PM'), (datetime.time(9, 30), '9:30 PM')], default=django.utils.timezone.now, max_length=10)),
                ('guests', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('comment', models.TextField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('settings_id', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
    ]
