# Generated by Django 3.2.18 on 2023-03-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
