# Generated by Django 3.2.18 on 2023-03-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.table'),
        ),
    ]
