# Generated by Django 3.2.18 on 2023-03-24 18:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('settings_id', models.IntegerField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, choices=[(datetime.time(5, 0), '5 PM'), (datetime.time(5, 30), '5:30 PM'), (datetime.time(6, 0), '6 PM')], default=django.utils.timezone.now, max_length=10),
        ),
    ]
