# Generated by Django 3.2.18 on 2023-03-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(default=False, max_length=200),
        ),
    ]
