# Generated by Django 3.2.18 on 2023-03-26 12:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20230324_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, choices=[(datetime.time(5, 0), '5 PM'), (datetime.time(5, 30), '5:30 PM'), (datetime.time(6, 0), '6 PM'), (datetime.time(6, 30), '6:30 PM'), (datetime.time(7, 0), '7 PM'), (datetime.time(7, 30), '7:30 PM'), (datetime.time(8, 0), '8 PM'), (datetime.time(8, 30), '8:30 PM'), (datetime.time(9, 0), '9 PM'), (datetime.time(9, 30), '9:30 PM')], default=django.utils.timezone.now, max_length=10),
        ),
    ]
