# Generated by Django 3.2.18 on 2023-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
