# Generated by Django 3.2.18 on 2023-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.TimeField(default='DURATION', max_length=10),
        ),
    ]
