# Generated by Django 3.2.18 on 2023-03-28 09:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.TimeField(choices=[(datetime.time(1, 30), '1:30'), (datetime.time(2, 0), '2:00')], default=django.utils.timezone.now, max_length=10),
        ),
    ]
