# Generated by Django 3.2.18 on 2023-03-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
    ]
