# Generated by Django 3.2.18 on 2023-03-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
